# Generated by Django 5.2.1 on 2025-05-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestNettCBT_authentication', '0002_remove_user_confirm_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
